### ISSUE TITLE
How to get monit-managed services restarted at deploy?

### ISSUE THREAD

**Issue by denishaskin** [apsoto/monit#1]
(Not really an issue, per se, but...)

I'm finding when I use this cookbook that monit itself gets restarted but the services it is monitoring do not.  Is there a recommended way to do this, or should I just make this part of my own recipes?

**Comment by apsoto** [comment]
In my experience any monitored services should start.  Do you use the monitrc LWRP?  It's supposed to restart monit whenever a new service is added and that should cause monit to pick up any new services.

**Comment by apsoto** [comment]
closing since I'm assuming you got it figured out?
