### ISSUE TITLE
Opscode tgz does not contain all the files

### ISSUE THREAD

**Issue by giorgio-v** [apsoto/monit#21]
The ubuntu 12 fix is missing.

**Comment by freerobby** [comment]
We haven't had a release since I added the ubuntu12 fix.

@apsoto Mind doing a release so we can get that out? If there's a way for you to give me permission to do it I'm happy to take that on.

**Comment by apsoto** [comment]
Yep,

What's your username?

Alex

**Comment by freerobby** [comment]
@apsoto freerobby

**Comment by apsoto** [comment]
Ok done.

Been so long I forgot exactly how it's done.  I think there's a knife
command to do it?

Alex
