### ISSUE TITLE
Call for new maintainers

### ISSUE THREAD

**Issue by apsoto** [apsoto/monit#37]
Hey All,

I really don't have the time to maintain this cookbook like I used to.  Lots of folks are adding pull requests and I don't have the capacity to test them.  

This cookbook predates a lot of the chef testing frameworks, so it's all been manual so far.

I'm looking for one or more volunteers to take over and bring this cookbook up to current best practices.  Please comment on issue if you are interested.

**Comment by yourabi** [comment]
Hi - since I use this and Monit is a dependency of one of my own public cookbooks ( https://github.com/yourabi/chef-puma ) I'd be interested in taking over.

**Comment by apsoto** [comment]
Anyone that is going to step up to take over please also let me know your cookbook community username so I can add you as a collaborator there so you can push releases.

**Comment by jwmarshall** [comment]
I'd be willing to jump in and help as a collaborator. We should get the project setup in TravisCI so we can run everything through foodcritic, including pull requests. I dont think I have a cookbook community account, but I can register one if it's needed.

**Comment by apsoto** [comment]
@yourabi  and @jwmarshall I've added you as collaborators.

**Comment by jwmarshall** [comment]
I'll get a feature branch for the TravisCI/Foodcritic stuff this week. Thanks!

**Comment by yourabi** [comment]
Awesome, thanks.

**Comment by jwmarshall** [comment]
Looks like I cant setup travis on a repository that I don't own. Do you want to set the project up in travis and I can add the config file that will run the tests? If you'd rather pass the reins to a new maintainer let me know.

**Comment by apsoto** [comment]
@jwmarshall ok I turned on travis.  Let me know if you need anything else.

**Comment by jwmarshall** [comment]
Foodcritic tests are now running, I will work on fixing the the tests that are failing before next week.

**Comment by yourabi** [comment]
Going to close this out...
