### ISSUE TITLE
Missing 'gem "foodcritic"' in Gemfile

### ISSUE THREAD

**Issue by yyamano** [apsoto/monit#41]
Could you add 'gem "foodcritic"' to Gemfile?

**Comment by jwmarshall** [comment]
:+1:

**Comment by yourabi** [comment]
Looks like this is already in the monit Gemfile. Thanks!

**Comment by jwmarshall** [comment]
Ya sorry I forgot to close this one last night. Thank you.

**Comment by yourabi** [comment]
No worries. In the future it is probably a good idea to request a pull-request and merge that instead of doing it yourself so that attribution is tracked and the PR can be reviewed. If you do add it yourself probably better to give the original author attribution. :-)

**Comment by jwmarshall** [comment]
I agree, we should also try to use git-flow or something so that we can more easily mange/package up commits/pull requests into proper versions. What do you think?

**Comment by yourabi** [comment]
Interesting thought.

1) We should probably take this discussion into its own thread.
2) Git-flow might be more complicated than this project needs. Larger projects like Homebrew do fairly well with a simple workflow.
3) There may not be a 1:1 between PRs and releases.
