### ISSUE TITLE
Cleanup foodcritic warnings 

### ISSUE THREAD

**Issue by yourabi** [apsoto/monit#44]
foodcritic -f any -B .

FC002: Avoid string interpolation where not required: ./templates/default/monitrc.erb:37
FC012: Use Markdown for README rather than RDoc: ./README.rdoc:1
FC015: Consider converting definition to a LWRP: ./definitions/monitrc.rb:1
FC019: Access node attributes in a consistent manner: ./attributes/default.rb:9
FC023: Prefer conditional attributes: ./recipes/default.rb:3
FC027: Resource sets internal attribute: ./recipes/default.rb:28
FC043: Prefer new notification syntax: ./definitions/monitrc.rb:6
FC043: Prefer new notification syntax: ./definitions/monitrc.rb:9
FC043: Prefer new notification syntax: ./definitions/monitrc.rb:20

**Comment by jwmarshall** [comment]
I have a feature branch that fixes most these, look at feature/please-the-foodcritic

**Comment by yourabi** [comment]
Cool. I've made a few of those fixes already but looks like duplicate work so I'll blow away my changes and let you merge yours in.

You might want to consider future feature branches in your own fork instead of against the main-repo so that we can use of PRs.

**Comment by yourabi** [comment]
BTW - forgot to add. let me know if you want to split up the work of tackling these. Happy to help out with this and will be good to get food critic happy again :-)

**Comment by jwmarshall** [comment]
Pretty sure I can still do a PR off the same repository, but I will create a fork for future work. I think my branch is complete, just didn't want to PR and merge right before going to bed.

**Comment by yourabi** [comment]
Cool - and wise choice!

**Comment by yourabi** [comment]
Hey - how is this going?

Please let me know if you want to divide up the work.

I'd like to merge in some fixes and start chatting about cutting a release and would be good to have this squared away.

**Comment by yourabi** [comment]
Since this has gone stale closing as duplicate of newer #58
