### ISSUE TITLE
Tag a new stable version for opscode

### ISSUE THREAD

**Issue by albertsun** [apsoto/monit#47]
Is this ready for a new stable version on opscode? This repo doesn't seem to have tags, and the latest version at http://community.opscode.com/cookbooks/monit is 0.7.1

**Comment by yourabi** [comment]
Hi - good point. My feeling is we're probably not yet ready to tag a release as there are a still a few more commits that need to be merged in.

**Comment by yourabi** [comment]
This has been done - and will be done again shortly.
