### ISSUE TITLE
Cookbook out of date on Chef community site

### ISSUE THREAD

**Issue by whiteley** [apsoto/monit#52]
The newest version on the [community](http://community.opscode.com/cookbooks/monit) site is `0.7.1` and not the `0.7.3` available here. Could you upload this newer version please?

**Comment by yourabi** [comment]
Yep. Sorry about that. It will get corrected in the near future.

As an aside the community is moving towards Berkshelf which enables you to pull down versions from Github directly. Might want to check that out.

**Comment by whiteley** [comment]
No worries, thanks for updating it! We are heavily invested in Berkshelf as
well but upstream is definitely frowning on github usage in production
systems. This was a frequent topic at this year's Chef Conf, you can see a
related issue at https://github.com/berkshelf/berkshelf/issues/1174

On Sat, Jul 5, 2014 at 5:40 PM, Yousef Ourabi notifications@github.com
wrote:

> Yep. Sorry about that. It will get corrected in the near future.
> 
> As an aside the community is moving towards Berkshelf which enables you to
> pull down versions from Github directly. Might want to check that out.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/apsoto/monit/issues/52#issuecomment-48099985.

## 

Matt Whiteley mattwhiteley@gmail.com

**Comment by yourabi** [comment]
Newer version has been pushed recently - and another will be pushed soon. Closing this.
