### ISSUE TITLE
monitrc definition broken on ubuntu 12.04 with Chef 10.4.

### ISSUE THREAD

**Issue by freerobby** [apsoto/monit#8]
Steps to reproduce:

Create some cookbook with a recipe that has:
"include_recipe 'monit'"
"include_recipe 'monit::postfix'"

Run a chef deploy.

Get:

NameError: undefined local variable or method `name' for #<Chef::Recipe:0x7ffb38b81920>
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/recipe_definition_dsl_core.rb:56:in`method_missing'
/var/chef/cache/cookbooks/monit/definitions/monitrc.rb:15:in `from_file'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/recipe_definition_dsl_core.rb:50:in`instance_eval'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/recipe_definition_dsl_core.rb:50:in `method_missing'
/var/chef/cache/cookbooks/monit/recipes/postfix.rb:3:in`from_file'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/cookbook_version.rb:578:in `load_recipe'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/language_include_recipe.rb:40:in`include_recipe'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/language_include_recipe.rb:27:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/language_include_recipe.rb:27:in`include_recipe'
/var/chef/cache/cookbooks/tester/recipes/monit.rb:4:in `from_file'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/cookbook_version.rb:578:in`load_recipe'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/language_include_recipe.rb:40:in `include_recipe'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/language_include_recipe.rb:27:in`each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/mixin/language_include_recipe.rb:27:in `include_recipe'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/run_context.rb:72:in`load'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/run_context.rb:69:in `each'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/run_context.rb:69:in`load'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/client.rb:195:in `setup_run_context'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/client.rb:159:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/client.rb:239:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/client.rb:229:in`loop'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application/client.rb:229:in `run_application'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/../lib/chef/application.rb:67:in`run'
/usr/lib/ruby/gems/1.8/gems/chef-0.10.4/bin/chef-client:26
/usr/bin/chef-client:19:in `load'

**Comment by freerobby** [comment]
I have this fixed here, FYI: https://github.com/shareaholic/chef-monit/commit/dd933ca6de622f48400ac96c0e4874f532e24236

I'm making a few feature improvements as well. I'll send a pull request when everything is done.

**Comment by apsoto** [comment]
great, thanks

**Comment by cmer** [comment]
+1

**Comment by yourabi** [comment]
Hi @freerobby - I assume we can close this PR... please reopen if this is still an issue.
